; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Password Manager"
#define MyAppVersion "1.0"
#define MyAppPublisher "Jozsef Bali"
#define MyAppURL "https://github.com/Fenrir-Codes"
; JAVÍTVA: Most már a te valódi indítófájlod neve szerepel itt!
#define MyAppExeName "PasswordManager.exe"

[Setup]
AppId={{97D64A29-23D4-4BCF-BD35-4DA0A7C608F4}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
; JAVÍTVA: Átrakva Local AppData-ba, hogy az .exe mellett jöhessen létre a pmdb.db!
DefaultDirName={localappdata}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; JAVÍTVA: A kész telepítőfájl neve a könnyebb érthetőségért
OutputBaseFilename=Password Manager - Setup
SolidCompression=yes
WizardStyle=modern dynamic
; JAVÍTVA: A kész telepítőt azonnal kiteszi neked az Asztalodra
OutputDir=userdesktop

[Languages]
Name: "hungarian"; MessagesFile: "compiler:Languages\Hungarian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; JAVÍTVA: Kiszedtem az Inno Setup saját példafájlját, és csak a te 3 fájlod maradt:
Source: "H:\C# Project Reopsitories\repos\PasswordManager\PasswordManager\bin\Release\net10.0-windows7.0\publish\e_sqlite3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "H:\C# Project Reopsitories\repos\PasswordManager\PasswordManager\bin\Release\net10.0-windows7.0\publish\PasswordManager.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "H:\C# Project Reopsitories\repos\PasswordManager\PasswordManager\bin\Release\net10.0-windows7.0\publish\PasswordManager.pdb"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent