<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<PublishSingleFile>true</PublishSingleFile>
	<SelfContained>false</SelfContained>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Vault.png" />
    <None Remove="VaultIcon.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="PMIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Vault.png" />
    <Resource Include="VaultIcon.png" />
  </ItemGroup>

	<PropertyGroup>
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>false</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<ApplicationIcon>PMIcon.ico</ApplicationIcon>
	</PropertyGroup>

</Project>
